//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace snap_lab_4_LINQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpartanTable
    {
        public string title { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string university { get; set; }
        public string courseTaken { get; set; }
        public string mark { get; set; }
    }
}
